### ISSUE TITLE
Can't handle vdf files that contain non-standard unicode characters

### ISSUE THREAD

**Issue by cbartondock** [node-steam/vdf#2]
I'm the active developer on Steam Rom Manager and we use this library. However I have noticed recently complaints from my non English speaking users that their arabic characters etc are breaking SRM. I've tracked it down to this, basically parse/stringify fail when non-standard unicode characters (arabic, chinese characters, emojis, etc) are involved.

If you could fix this that would be huge for us. Thank you!

**Comment by lenovouser** [comment]
@cbartondock how did you solve it? Could you give me an example `.vdf`
