### ISSUE TITLE
Support comments in VDF/KeyValues files

### ISSUE THREAD

**Issue by ProdigySim** [node-steam/vdf#4]
SourceMod for Valve titles uses ["GameData" files ](https://github.com/alliedmodders/sourcemod/blob/master/gamedata/sdktools.games/game.left4dead2.txt), which are keyvalues files, but they often have comments placed in them as `/* ... */` multiline syntax. It would be nice to be able to parse these with this tool.

```
error: Uncaught SyntaxError: VDF | Parse: Invalid syntax on line 4
                throw new SyntaxError(`VDF | Parse: Invalid syntax on line ${i + 1}`);
```

**Comment by webman** [comment]
@ProdigySim, **JSON** doesn't support comments natively.

But there is a **JSONC** format that supports this.

**Comment by ProdigySim** [comment]
@webman I'm talking about VDF, not JSON.

Edit: To clarify, stripping out the comments would be an acceptable solution for my use case. I just need the parser to not die when hitting comments.

**Comment by AndreasWJ** [comment]
@ProdigySim: I was reading one of those files today, had the same issue as you more or less. I read resource/csgo_english.txt, a game file from CSGO similar to the one you linked.

The first thing I suggest doing is to put print statements in @node-steam/vdf's module, what's important to print is the 'lines' array. What I gathered from my debugging was that this array contained weird sequences of characters:
`\x00M\x00o\x00n\x00t\ ...`
Which lead me to figure out what encoding the file was written in. Here's a simple way of doing so: https://stackoverflow.com/a/13464816/2036186

Once you have the encoding down, change from utf-8 or whatever in your fs.readFile(...), to the actual file encoding.

**Comment by lenovouser** [comment]
@ProdigySim @webman @AndreasWJ please try `v2.2.0` and tell me if it works
